config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'books#index'
    resources :books
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
# application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    # current_user.locale
    # request.env["HTTP_ACCEPT_LANGUAGE"]
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book_items = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book_item = Book.new(params.require(:book).permit(:title, :description, :year))

    respond_to do |format|
      if @book_item.save
        format.html { redirect_to books_path, notice: 'Book was updated'}
      else
        format.html { render :new}
      end
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params.require(:book).permit(:title, :description, :year))
        format.html { redirect_to books_path, notice: 'The book was updated' }
      else
        format.html { render :edit }
      end

    end
  end

  def show
    @book_item = Book.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1><%=t '.update_book' %></h1>

<%= form_for(@book) do |f| %>
  <div class="input_item">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="input_item">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="input_item">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit'), :class => 'submit_button' %>
  </div>


<% end %>

app/views/books/index.html.erb
<h1> <%= t '.listing' %> </h1>

<table class='table table-striped'>
  <thead>
  <tr>
    <th> <%= t'.title' %></th>
    <th> <%= t '.description' %></th>
    <th> <%= t '.year' %></th>
    <th colspan="3"></th>

  </tr>
  </thead>


    <% @book_items.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.year %></td>
        <td><div><%= link_to t('.edit') , edit_book_path(book.id) %></div></td>
        <td><div><%= link_to t('.show'), book_path(book.id) %></div></td>

      </tr>
    <% end %>
    </tbody>
    </table>

<br>

<div class="create"><%= link_to t('.create'), new_book_path %></div>

app/views/books/new.html.erb
<h1><%=t '.create_book' %></h1>

<%= form_for(@book) do |f| %>
  <div class="input_item">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="input_item">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="input_item">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit'), :class => 'submit_button' %>
  </div>


<% end %>

app/views/books/show.html.erb
<div class="show">
  <div id="labels"> <%= t'.title' %> </div>
  <div> <%= @book_item.title %></div>
  <div id="labels"> <%= t'.description' %> </div>
  <div> <%= @book_item.description %></div>
  <div id="labels"> <%= t'.year' %> </div>
  <div> <%= @book_item.year %></div>

  <div id="back"><%= link_to t('.back'), root_path %></div>
</div>

app/views/layouts/_header.html.erb
<div class="app-header">

  <%= content_tag :li do %>
    <%= link_to t('header.english'), locale: :en %>
  <% end  %>

  <%= content_tag :li do %>
    <%= link_to t('header.italian'), locale: :it  %>
  <% end %>

  <%= content_tag :li do %>
    <%= link_to t('header.german'), locale: :de %>
  <% end  %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MultilingualApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>